# 1. المعرفات الخاصة بالمشروع (ممنوع تغييرها)
sonar.projectKey=HussienMostafa1_ultimate-devsecops-node-project
sonar.organization=hussienmostafa1

# 2. تحديد مكان الكود الأساسي (ده اللي هيتفتش أمنياً)
sonar.sources=app/src

# 3. استثناء المجلدات اللي مش عاوزين نضيع وقت فيها (زي المكتبات الخارجية)
# السطر ده بيمنع السونار إنه يدخل في "متاهة" الـ node_modules
sonar.exclusions=**/node_modules/**, **/dist/**, app/src/tests/**

# 4. تحديد مكان ملفات الاختبار (عشان يحسب الـ Coverage)
sonar.tests=app/src/tests
sonar.test.inclusions=**/*.test.js

# 5. مكان تقرير الاختبارات (الخريطة اللي بتعرفه إحنا اختبرنا إيه)
sonar.javascript.lcov.reportPaths=app/src/coverage/lcov.info

# 6. لغة تشفير الملفات
sonar.sourceEncoding=UTF-8
