name: CI/CD DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    # 💡 دي أهم حتة: بتقوله كل الأوامر اللي جاية "سكينتها" جوه app/src
    defaults:
      run:
        working-directory: app/src

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # 💡 هنا بنقوله يدور على ملف الـ lock جوه الفولدر الصح عشان الـ Cache يشتغل
          cache: 'npm'
          cache-dependency-path: app/src/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test
